version: '3'
services:
    lumen.api:
        container_name: api-server-technical
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8010}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini'
        networks:
            - technical
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: '${POSTGRES_DB}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            SERVICE_TAGS: '${SERVICE_TAGS}'
            SERVICE_NAME: '${SERVICE_NAME}'
        volumes:
            - ./dbdata:/var/lib/postgresql/data
            - ./docker/8.3/postgresql/postgresql.conf:/usr/share/postgresql/postgresql.conf
        networks:
            - technical
networks:
    technical:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
